In [1]:
#libraries
import cv2
from sklearn.cluster import KMeans

github repo


video downscale
unterabtastung

In [2]:
vid = cv2.VideoCapture('IMG_2525.MOV')
frames=[]
while(vid.isOpened()):
    # Capture frame-by-frame
    ret, frame = vid.read()
    frames.append(frame)
    if ret:
        # Display the resulting frame
        cv2.imshow('frame',frame)
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break
    else:
        break
vid.release()
cv2.destroyAllWindows()

In [3]:
len(frames)

4278

In [ ]:
# cv2.imshow('frame',frames[200])

Dominant Color Extractor

In [4]:
class DominantColors:
    CLUSTERS = None
    IMAGE = None
    COLORS = None
    LABELS = None
    def __init__(self, image, clusters=3):
        self.CLUSTERS = clusters
        self.IMAGE = image
    def dominantColors(self):
        #read image
        img = cv2.imread(self.IMAGE)
        
        #convert to rgb from bgr
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
                
        #reshaping to a list of pixels
        img = img.reshape((img.shape[0] * img.shape[1], 3))
        
        #save image after operations
        self.IMAGE = img
        
        #using k-means to cluster pixels
        kmeans = KMeans(n_clusters = self.CLUSTERS)
        kmeans.fit(img)
        
        #the cluster centers are our dominant colors.
        self.COLORS = kmeans.cluster_centers_
        
        #save labels
        self.LABELS = kmeans.labels_
        
        #returning after converting to integer from float
        return self.COLORS.astype(int)
    def dominant2(self):
        img = self.IMAGE
        self.IMAGE = img
        
        img = img.reshape((img.shape[0] * img.shape[1], 3))
        
        #using k-means to cluster pixels
        kmeans = KMeans(n_clusters = self.CLUSTERS)
        kmeans.fit(img)
        
        #the cluster centers are our dominant colors.
        self.COLORS = kmeans.cluster_centers_
        
        #save labels
        self.LABELS = kmeans.labels_
        
        #returning after converting to integer from float
        return self.COLORS.astype(int)

In [15]:
frames[0]

array([[[ 39,  45,  54],
        [ 37,  43,  52],
        [ 32,  38,  47],
        ...,
        [ 24,  31,  58],
        [ 24,  31,  58],
        [ 24,  31,  58]],

       [[ 38,  44,  53],
        [ 36,  42,  51],
        [ 32,  38,  47],
        ...,
        [ 25,  32,  59],
        [ 24,  31,  58],
        [ 24,  31,  58]],

       [[ 36,  42,  51],
        [ 34,  40,  49],
        [ 30,  36,  45],
        ...,
        [ 25,  32,  59],
        [ 24,  31,  58],
        [ 24,  31,  58]],

       ...,

       [[ 54,  62,  84],
        [ 53,  61,  83],
        [ 52,  60,  82],
        ...,
        [136, 163, 184],
        [136, 163, 184],
        [136, 163, 184]],

       [[ 49,  57,  79],
        [ 47,  55,  77],
        [ 47,  55,  77],
        ...,
        [134, 165, 181],
        [134, 165, 181],
        [134, 165, 181]],

       [[ 46,  54,  76],
        [ 46,  54,  76],
        [ 46,  54,  76],
        ...,
        [134, 165, 181],
        [134, 165, 181],
        [134, 165, 181]]

1. look up list
2. color map to string
3. histogram

4. k-means selber mit color list
nearest neighbour search sklearn

In [5]:
img = frames[0]
clusters = 5
dc = DominantColors(img, clusters) 
colors = dc.dominant2()
# colors = dc.dominantColors()
print(colors)

[[ 32  31  34]
 [128 172 191]
 [ 91 100 114]
 [246 250 250]
 [ 58  66  67]]


In [6]:
img = frames[1]
clusters = 5
dc = DominantColors(img, clusters) 
colors = dc.dominant2()
# colors = dc.dominantColors()
print(colors)

[[127 170 189]
 [ 32  31  34]
 [ 58  65  66]
 [246 250 250]
 [ 90 100 113]]


In [26]:
import numpy as np
img = cv2.imread('image2.png')
#convert to rgb from bgr
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
#reshaping to a list of pixels
img = img.reshape((img.shape[0] * img.shape[1], 3))
# using k-means to cluster pixels
# kmeans = KMeans(n_clusters = self.CLUSTERS)
# kmeans.fit(img)
img1 = frames[0].reshape((frames[0].shape[0] * frames[0].shape[1], 3))
# np.s(np.ravel(frames[0],))

In [27]:
np.shape(img)
np.shape(img1)

(2073600, 3)